# Setup
title:        itho.co
tagline:      Android development
baseurl:      ""
paginate:     1
permalink:    /blog/:year/:month/:day/:title

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
