# Setup
title:      itho
tagline:    software development
baseurl:    ""
paginate:   1
permalink:  /blog/:year/:month/:day/:title

# About/contact
author:
  name:     Ieuan Thomas
  url:      http://itho.co 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
highlighter: rouge
